- index.js
This app didn't work on Windows as the config file location is different, see here https://github.com/alacritty/alacritty#windows 
It now does :)
> Add support for Windows

- bin/cli.js
> fix: do not apply theme if it's undefined

- index.js
You have created a very nice CLI and I much appreciate it.
In order for it to be useful to many more people, I created this piece of code.
Alacritty searches for it's config file in a number of locations and now your cli confirms to this search pattern (and order of preference).
For more information about this see: https://github.com/alacritty/alacritty#configuration
> Search alacritty config file in all possible locations

- index.js
> Fixed incorrect fs.existsSync(configPath) call

- .github/workflows/main.yml
- .github/workflows/pull_requests.yml
I didn't see the tests are running on GitHub actions, I thought you are
running only the linter.
> fix build name

- .husky/pre-commit
- package.json
Recently, I pushed a PR without running the `lint` this `husky` library
will prevent it.
> improvement: add husky

- index.js
> Handle empty config files gracefully

- themes/Tokyonight_Day.yml
- themes/Tokyonight_Night.yml
- themes/Tokyonight_Storm.yml
reference [tokyonight.nvim](https://github.com/folke/tokyonight.nvim)
> Add Tokyo Night Colors

- index.js
- src/helpers/index.js
- test/index.test.js
Wow, it's incredible to have this chance, change things here just means learn 🙏
> Improve testing 🔥🐛

- index.js
- test/index.test.js
> fix: stop removing existing comments on the alacritty file

- index.js
- src/helpers/index.js
- test/src/helpers/index.test.js
create pathToAlacrittyFile method, which determines the path to the alacritty.yml file depending on the OS.
> chore: clean createConfigFile method

- settings.js
- src/helpers/index.js
- test/src/helpers/index.test.js
related issue #44
related pr #45
> fix: set project dir as rootDirectory

- src/helpers/index.js
> fix: possible alacritty locations

- themes/github_dark.yml
- themes/github_dark_default.yml
- themes/github_dimmed.yml
- themes/github_light.yml
- themes/github_light_default.yml
Closes #75
Themes from [https://github.com/projekt0n/github-nvim-theme](https://github.com/projekt0n/github-nvim-theme)
> improve: add github themes

- themes/ShadesOfPurple.yml
Adds the ShadesOfPurple theme from https://github.com/ahmadawais/shades-of-purple-alacritty
> build(theme): add ShadesOfPurple

- .github/workflows/main.yml
- .github/workflows/pull_requests.yml
> BREAKING CHANGE: Remove Node 12 Support

- package.json
> Fix(engines): Remove support for node 12

- package.json
> feat(dependencies): Update dependencies

- bin/cli.js
- package.json
- src/helpers/index.js
This will be called once the `alacritty-themes` command gets executed.
Related #131
> feat(cli): Add createBackup method

- themes/Alabaster.yml
Add Alabaster minimal theme
Based by color scheme from: https://github.com/tonsky/vscode-theme-alabaster
> Add Alabaster theme

- README.md
> docs(backups): Add how to remove backups

- alacritty.yml
Closes #169 
Related:
- https://github.com/alacritty/alacritty/commit/2a676dfad837d1784ed0911d314bc263804ef4ef
> refactor(alacritty-template): Fix thin strokes

- src/helpers/index.js
> fix(backup): fix where to find the alacritty file path

- themes/paper-theme.yml
Hi Rajesagar,
I hope you're well.
Here is the Paper theme for Alacritty. The original palette is c/o Yorick Peterse.
Cheers,
Sam
> feat(theme): added Paper theme

- themes/Fedora.yaml
Adding Fedora theme based on color pallet from gnome terminal on fedora.
> fix(theme): Add Fedora Theme

- themes/Alabaster.dark.yml
- themes/Alabaster.yml
Add Alabaster minimal dark theme
Based by color scheme from: https://github.com/gargakshit/vscode-theme-alabaster-dark
> Add Alabaster dark theme
